apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        configChecksum: {{ .Files.Get "files/envoy.yaml" | sha256sum }}
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-controlplane
  template:
    metadata:
      labels:
        app: envoy-controlplane
    spec:
      containers:
        - name: control-plane
          image: "495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/envoy-controlplane:0.0.1"
          ports:
            - containerPort: 18000
              name: grpc
            - containerPort: 9000
              name: rest
