name: Create Manifest and Deploy

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: hugh-nguyen/cortex

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests ≈

      - name: Create Application Version Manifest
        run: python -m cortex.create_application_version_manifest --clone --app_name ${{ inputs.app_name }}

  deploy-app-version:
    runs-on: ubuntu-latest
    needs: create-manifest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: hugh-nguyen/cortex

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests boto3

      - name: Create Application Version Manifest
        run: python -m cortex.create_application_manifest --app_name ${{ inputs.app_name }} --
