name: Pull Manifests and Routes, then Deploy

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'The Cortex Command Repo to pull App Manifests and Routes from'
        required: true
        type: string

jobs:
  pull-manifests-and-routes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests boto3

      - name: Generate Application Manifests
        run: python -m cortex.1-pull-manifests-and-routes ${{ github.event.inputs.source_repo }}
        env:
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
